WebReport78/Controllers/ProtectDutyController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Diagnostics;
using WebReport78.Models;


namespace WebReport78.Controllers
{
    public class ProtectDutyController : Controller
    {
        private readonly ILogger<ProtectDutyController> _logger;
        private readonly XGuardContext _context;
        public ProtectDutyController(ILogger<ProtectDutyController> logger, XGuardContext context)
        {
            _logger = logger;
            _context = context;
        }

        public DateTime SwapMonthDay(string dateStr)
        {
            string[] parts = dateStr.Split('/');
            if (parts.Length != 3)
                throw new ArgumentException("Định dạng ngày không hợp lệ (phải là M/d/yyyy)");

            int month = int.Parse(parts[0]);
            int day = int.Parse(parts[1]);
            int year = int.Parse(parts[2]);

            // Đảo vị trí tháng <-> ngày
            return new DateTime(year, day, month);
        }

        private DateTime ParseExcelCellAsText(ExcelRange cell, int row)
        {
            if (cell?.Value == null || string.IsNullOrWhiteSpace(cell.Text))
                throw new ArgumentException($"Ô ngày trống tại dòng {row}");

            // Nếu Excel lưu dạng số serial date
            if (cell.Value is double serialDate)
            {
                var date = DateTime.FromOADate(serialDate);
                return SwapMonthDay(date.ToString("d/M/yyyy")); // Ví dụ: 1/8/2025
            }

            // Nếu là DateTime chuẩn
            if (cell.Value is DateTime dateTime)
            {
                string formattedDate = dateTime.ToString("d/M/yyyy"); // "1/8/2025"
                string[] parts = formattedDate.Split('/');
                string swapped = $"{parts[1].Trim()}/{parts[0].Trim()}/{parts[2].Trim()}"; // ngày/tháng/năm
                return SwapMonthDay(swapped); // Ví dụ: 1/8/2025
            }

            // Nếu Excel đã lưu sẵn dạng text
            return SwapMonthDay(cell.Text.Trim());
        }

        [HttpGet] // hiển thị form mới theo month cần tìm
        public IActionResult Index(string monthYearImport)
        {
            // hiện nút lưu khi import file
            ViewData["CanSave"] = false;

            // disable nút sửa xóa khi tháng đã qua
            bool disableSave = false;

            // Nếu không có monthYearImport, lấy tháng hiện tại
            if (string.IsNullOrEmpty(monthYearImport))
            {
                monthYearImport = DateTime.Now.ToString("yyyy-MM");
            }

            var dateNow = DateTime.Now;
            if (!string.IsNullOrEmpty(monthYearImport) && DateTime.TryParseExact(monthYearImport, "yyyy-MM", null, System.Globalization.DateTimeStyles.None, out var parsedMonthYear))
            {
                // Kiểm tra tháng đã qua
                if (parsedMonthYear.Year < dateNow.Year ||
                    (parsedMonthYear.Year == dateNow.Year && parsedMonthYear.Month < dateNow.Month))
                {
                    disableSave = true;
                }

                var duties = _context.DutyShifts
                    .Where(d => d.MothYearImport.Year == parsedMonthYear.Year &&
                                d.MothYearImport.Month == parsedMonthYear.Month)
                    .OrderBy(d => d.Dateduty)
                    .ToList();

                ViewData["MonthYearImport"] = monthYearImport;
                ViewData["DisableSave"] = disableSave;

                if (!duties.Any())
                {
                    TempData["Error"] = $"Chưa có dữ liệu cho tháng {monthYearImport}.";
                }
                return View(duties);
            }

            TempData["Error"] = "Định dạng tháng/năm không hợp lệ.";
            ViewData["DisableSave"] = true; // Disable luôn nếu format sai
            return View(new List<DutyShift>());
        }


        [HttpPost]
        public IActionResult ImportFile(IFormFile file, string monthYearImport)
        {
            if (file == null || file.Length == 0 || string.IsNullOrEmpty(monthYearImport))
            {
                TempData["Error"] = "Vui lòng chọn file và tháng.";
                return RedirectToAction(nameof(Index));
            }

            if (!DateTime.TryParseExact(monthYearImport, "yyyy-MM", null, System.Globalization.DateTimeStyles.None, out var parsedMonthYear))
            {
                TempData["Error"] = "Định dạng tháng/năm không hợp lệ.";
                return RedirectToAction(nameof(Index));
            }
            var dataDuty = new List<DutyShift>();
            var dateNow = DateTime.Now;
            try
            {
                if (parsedMonthYear.Year < dateNow.Year || parsedMonthYear.Year == dateNow.Year && parsedMonthYear.Month < dateNow.Month)
                {
                    TempData["Error"] = $"Không nhập cho tháng {monthYearImport} vì tháng đã qua";
                    return RedirectToAction(nameof(Index));
                }
                else
                {

                    using (var stream = new MemoryStream())
                    {
                        file.CopyTo(stream);
                        stream.Position = 0;
                        using (var package = new ExcelPackage(stream))
                        {
                            var worksheet = package.Workbook.Worksheets[0];
                            var rowCount = worksheet.Dimension.Rows;
                            for (int row = 2; row <= rowCount; row++) // bắt đầu từ dòng 2 dòng 1 mặc định là tiêu đề
                            {
                                var parsedDate = ParseExcelCellAsText(worksheet.Cells[row, 1], row);
                                var duties = new DutyShift
                                {
                                    Dateduty = DateOnly.FromDateTime(parsedDate),
                                    Fullname = worksheet.Cells[row, 2].Text?.Trim() ?? "",
                                    Rankk = worksheet.Cells[row, 3].Text?.Trim() ?? "",
                                    Department = worksheet.Cells[row, 4].Text?.Trim() ?? "",
                                    Phonenumber = worksheet.Cells[row, 5].Text?.Trim() ?? "",
                                    MothYearImport = new DateOnly(parsedMonthYear.Year, parsedMonthYear.Month, 1),
                                    DateCreated = DateTime.Now
                                };
                                // thêm đối tuong duty vua tao và danh sach để ty lưu và db
                                dataDuty.Add(duties);
                            }
                        }
                    }
                }
                ViewData["MonthYearImport"] = monthYearImport;
                TempData["ImportedData"] = System.Text.Json.JsonSerializer.Serialize(dataDuty); // Lưu tạm dữ liệu vào TempData
                ViewData["CanSave"] = true;
                return View("Index", dataDuty);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi import file Excel.");
                TempData["Error"] = ex.Message;
                ViewData["CanSave"] = false;
                return RedirectToAction(nameof(Index));
            }
        }


        [HttpPost]
        public IActionResult SaveImportData(string monthYearImport)
        {
            if (string.IsNullOrEmpty(monthYearImport) || !TempData.ContainsKey("ImportedData"))
            {
                TempData["Error"] = "Không có dữ liệu để lưu.";
                return RedirectToAction(nameof(Index));
            }

            // Parse monthYearImport sang DateTime để lấy Year &Month
            if (!DateTime.TryParseExact(monthYearImport, "yyyy-MM", null, System.Globalization.DateTimeStyles.None, out var parsedDate))
            {
                TempData["Error"] = "Định dạng tháng/năm không hợp lệ.";
                return RedirectToAction(nameof(Index));
            }
            try
            {
                var importData = System.Text.Json.JsonSerializer.Deserialize<List<DutyShift>>(
                (string)TempData["ImportedData"]);

                var existingDuties = _context.DutyShifts
                    .Where(d => d.MothYearImport.Year == parsedDate.Year &&
                                d.MothYearImport.Month == parsedDate.Month)
                    .ToList();
                _context.DutyShifts.RemoveRange(existingDuties);

                // Thêm dữ liệu mới
                _context.DutyShifts.AddRange(importData.OrderBy(d => d.Dateduty));
                _context.SaveChanges();

                TempData["Success"] = "Dữ liệu đã được lưu thành công.";
                ViewData["CanSave"] = false; // Ẩn nút Lưu
                return RedirectToAction(nameof(Index), new { monthYearImport });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi lưu dữ liệu vào cơ sở dữ liệu.");
                TempData["Error"] = $"Lưu dữ liệu thất bại: {ex.Message}";
                return RedirectToAction(nameof(Index), new { monthYearImport });
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DutyShift model, string monthYearImport)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("Create", model); // Trả về partial view nếu validation thất bại
            }
            var dateNow = DateTime.Now;
            try
            {
                if (!DateTime.TryParseExact(monthYearImport, "yyyy-MM", null, System.Globalization.DateTimeStyles.None, out var parsedMonthYear))
                {
                    ModelState.AddModelError("", "Định dạng tháng/năm không hợp lệ.");
                    return PartialView("Create", model);
                }

WebReport78/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebReport78</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebReport78.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ProtectDuty" asp-action="Index">HCKT-Report</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @((ViewContext.RouteData.Values["Controller"]?.ToString() == "ProtectDuty" && ViewContext.RouteData.Values["Action"]?.ToString() == "Index") ? "active" : "")"
                               asp-area="" asp-controller="ProtectDuty" asp-action="Index">Trực Ban</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @((ViewContext.RouteData.Values["Controller"]?.ToString() == "InOut" && ViewContext.RouteData.Values["Action"]?.ToString() == "Index") ? "active" : "")"
                               asp-area="" asp-controller="InOut" asp-action="Index">Vào/Ra</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebReport78/Views/Shared/_toastNotice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@if (TempData["Success"] != null)
{
    <div class="toast align-items-center text-bg-success border-0 position-fixed top-0 end-0 m-3" role="alert" aria-live="assertive" aria-atomic="true" style="z-index: 1055;">
        <div class="d-flex">
            <button type="button" class="btn-check me-2 m-auto " data-bs-dismiss="toast" aria-label="Check"></button>
            <div class="toast-body">
                <span class="fs-4">
                    ✅
                </span>
                @TempData["Success"]
            </div>
            <button type="button" class="btn-close btn-warning me-2 m-auto " data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="toast align-items-center text-bg-danger border-0 position-fixed top-0 end-0 m-3" role="alert" aria-live="assertive" aria-atomic="true" style="z-index: 1055;">
        <div class="d-flex">
            <div class="toast-body">
                <span class="fs-4">
                    ⛔
                </span>
                @TempData["Error"]
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
}